/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Asset': { kind: 'OBJECT'; name: 'Asset'; fields: { 'alt': { name: 'alt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'blurhash': { name: 'blurhash'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'filename': { name: 'filename'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'height': { name: 'height'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'mimeType': { name: 'mimeType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'responsiveImage': { name: 'responsiveImage'; type: { kind: 'OBJECT'; name: 'ResponsiveImage'; ofType: null; } }; 'size': { name: 'size'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'width': { name: 'width'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'Author': { kind: 'OBJECT'; name: 'Author'; fields: { '_createdAt': { name: '_createdAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_firstPublishedAt': { name: '_firstPublishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_modelApiKey': { name: '_modelApiKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; '_publishedAt': { name: '_publishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_seoMetaTags': { name: '_seoMetaTags'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Tag'; ofType: null; }; }; }; } }; '_status': { name: '_status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_updatedAt': { name: '_updatedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'bio': { name: 'bio'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'photo': { name: 'photo'; type: { kind: 'OBJECT'; name: 'Asset'; ofType: null; } }; }; };
    'AuthorFilter': { kind: 'INPUT_OBJECT'; name: 'AuthorFilter'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_status'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_createdAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_updatedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_publishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_firstPublishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'bio'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'photo'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'AND'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'AuthorFilter'; ofType: null; }; }; }; defaultValue: null }, { name: 'OR'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'AuthorFilter'; ofType: null; }; }; }; defaultValue: null }]; };
    'AuthorMeta': { kind: 'OBJECT'; name: 'AuthorMeta'; fields: { 'count': { name: 'count'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'AuthorOrderBy': { name: 'AuthorOrderBy'; enumValues: '_createdAt_ASC' | '_createdAt_DESC' | '_updatedAt_ASC' | '_updatedAt_DESC' | '_publishedAt_ASC' | '_publishedAt_DESC' | '_firstPublishedAt_ASC' | '_firstPublishedAt_DESC' | 'name_ASC' | 'name_DESC' | 'bio_ASC' | 'bio_DESC' | 'photo_ASC' | 'photo_DESC'; };
    'Boolean': unknown;
    'BooleanFilter': { kind: 'INPUT_OBJECT'; name: 'BooleanFilter'; isOneOf: false; inputFields: [{ name: 'eq'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'exists'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'BooleanMultiLocaleField': { kind: 'OBJECT'; name: 'BooleanMultiLocaleField'; fields: { 'locale': { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; }; };
    'Category': { kind: 'OBJECT'; name: 'Category'; fields: { '_createdAt': { name: '_createdAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_firstPublishedAt': { name: '_firstPublishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_modelApiKey': { name: '_modelApiKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; '_publishedAt': { name: '_publishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_seoMetaTags': { name: '_seoMetaTags'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Tag'; ofType: null; }; }; }; } }; '_status': { name: '_status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_updatedAt': { name: '_updatedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'cover_image': { name: 'cover_image'; type: { kind: 'OBJECT'; name: 'Asset'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'icon': { name: 'icon'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'sort_order': { name: 'sort_order'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'CategoryFilter': { kind: 'INPUT_OBJECT'; name: 'CategoryFilter'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_status'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_createdAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_updatedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_publishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_firstPublishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'slug'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'description'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'cover_image'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'icon'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'sort_order'; type: { kind: 'INPUT_OBJECT'; name: 'IntFilter'; ofType: null; }; defaultValue: null }, { name: 'AND'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'CategoryFilter'; ofType: null; }; }; }; defaultValue: null }, { name: 'OR'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'CategoryFilter'; ofType: null; }; }; }; defaultValue: null }]; };
    'CategoryMeta': { kind: 'OBJECT'; name: 'CategoryMeta'; fields: { 'count': { name: 'count'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'CategoryOrderBy': { name: 'CategoryOrderBy'; enumValues: '_createdAt_ASC' | '_createdAt_DESC' | '_updatedAt_ASC' | '_updatedAt_DESC' | '_publishedAt_ASC' | '_publishedAt_DESC' | '_firstPublishedAt_ASC' | '_firstPublishedAt_DESC' | 'name_ASC' | 'name_DESC' | 'slug_ASC' | 'slug_DESC' | 'description_ASC' | 'description_DESC' | 'cover_image_ASC' | 'cover_image_DESC' | 'icon_ASC' | 'icon_DESC' | 'sort_order_ASC' | 'sort_order_DESC'; };
    'ColorField': { kind: 'OBJECT'; name: 'ColorField'; fields: { 'alpha': { name: 'alpha'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'blue': { name: 'blue'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'green': { name: 'green'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'hex': { name: 'hex'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'red': { name: 'red'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'DateTimeFilter': { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; isOneOf: false; inputFields: [{ name: 'eq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'neq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'gt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'lt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'gte'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'lte'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'exists'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'Float': unknown;
    'FloatFilter': { kind: 'INPUT_OBJECT'; name: 'FloatFilter'; isOneOf: false; inputFields: [{ name: 'eq'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'neq'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'gt'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'lt'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'gte'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'lte'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'exists'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'FloatMultiLocaleField': { kind: 'OBJECT'; name: 'FloatMultiLocaleField'; fields: { 'locale': { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'ID': unknown;
    'ImageTransformParams': { kind: 'INPUT_OBJECT'; name: 'ImageTransformParams'; isOneOf: false; inputFields: [{ name: 'width'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'height'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'fit'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'quality'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'format'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'gravity'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'dpr'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }]; };
    'Int': unknown;
    'IntFilter': { kind: 'INPUT_OBJECT'; name: 'IntFilter'; isOneOf: false; inputFields: [{ name: 'eq'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'neq'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'gt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'lt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'gte'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'lte'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'exists'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'IntMultiLocaleField': { kind: 'OBJECT'; name: 'IntMultiLocaleField'; fields: { 'locale': { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'JSON': unknown;
    'LatLonField': { kind: 'OBJECT'; name: 'LatLonField'; fields: { 'latitude': { name: 'latitude'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'longitude': { name: 'longitude'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'MatchesFilter': { kind: 'INPUT_OBJECT'; name: 'MatchesFilter'; isOneOf: false; inputFields: [{ name: 'pattern'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'caseSensitive'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'Post': { kind: 'OBJECT'; name: 'Post'; fields: { '_createdAt': { name: '_createdAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_firstPublishedAt': { name: '_firstPublishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_modelApiKey': { name: '_modelApiKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; '_publishedAt': { name: '_publishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_seoMetaTags': { name: '_seoMetaTags'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Tag'; ofType: null; }; }; }; } }; '_status': { name: '_status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_updatedAt': { name: '_updatedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'author': { name: 'author'; type: { kind: 'OBJECT'; name: 'Author'; ofType: null; } }; 'category': { name: 'category'; type: { kind: 'OBJECT'; name: 'Category'; ofType: null; } }; 'content': { name: 'content'; type: { kind: 'OBJECT'; name: 'StructuredText'; ofType: null; } }; 'cover_image': { name: 'cover_image'; type: { kind: 'OBJECT'; name: 'Asset'; ofType: null; } }; 'excerpt': { name: 'excerpt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'featured': { name: 'featured'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'gallery': { name: 'gallery'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Asset'; ofType: null; }; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'published_date': { name: 'published_date'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'reading_time': { name: 'reading_time'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'related_posts': { name: 'related_posts'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Post'; ofType: null; }; }; } }; 'seo_field': { name: 'seo_field'; type: { kind: 'OBJECT'; name: 'SeoField'; ofType: null; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'PostFilter': { kind: 'INPUT_OBJECT'; name: 'PostFilter'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_status'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_createdAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_updatedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_publishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_firstPublishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: 'title'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'slug'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'excerpt'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'cover_image'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'author'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'category'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'published_date'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'reading_time'; type: { kind: 'INPUT_OBJECT'; name: 'IntFilter'; ofType: null; }; defaultValue: null }, { name: 'featured'; type: { kind: 'INPUT_OBJECT'; name: 'BooleanFilter'; ofType: null; }; defaultValue: null }, { name: 'AND'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'PostFilter'; ofType: null; }; }; }; defaultValue: null }, { name: 'OR'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'PostFilter'; ofType: null; }; }; }; defaultValue: null }]; };
    'PostMeta': { kind: 'OBJECT'; name: 'PostMeta'; fields: { 'count': { name: 'count'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'PostOrderBy': { name: 'PostOrderBy'; enumValues: '_createdAt_ASC' | '_createdAt_DESC' | '_updatedAt_ASC' | '_updatedAt_DESC' | '_publishedAt_ASC' | '_publishedAt_DESC' | '_firstPublishedAt_ASC' | '_firstPublishedAt_DESC' | 'title_ASC' | 'title_DESC' | 'slug_ASC' | 'slug_DESC' | 'excerpt_ASC' | 'excerpt_DESC' | 'cover_image_ASC' | 'cover_image_DESC' | 'author_ASC' | 'author_DESC' | 'category_ASC' | 'category_DESC' | 'published_date_ASC' | 'published_date_DESC' | 'reading_time_ASC' | 'reading_time_DESC' | 'featured_ASC' | 'featured_DESC'; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { '_allAuthorsMeta': { name: '_allAuthorsMeta'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AuthorMeta'; ofType: null; }; } }; '_allCategorysMeta': { name: '_allCategorysMeta'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CategoryMeta'; ofType: null; }; } }; '_allPostsMeta': { name: '_allPostsMeta'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PostMeta'; ofType: null; }; } }; '_allSiteSettingssMeta': { name: '_allSiteSettingssMeta'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SiteSettingsMeta'; ofType: null; }; } }; '_site': { name: '_site'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SiteInfo'; ofType: null; }; } }; 'allAuthors': { name: 'allAuthors'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Author'; ofType: null; }; }; }; } }; 'allCategorys': { name: 'allCategorys'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Category'; ofType: null; }; }; }; } }; 'allPosts': { name: 'allPosts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Post'; ofType: null; }; }; }; } }; 'allSiteSettingss': { name: 'allSiteSettingss'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SiteSettings'; ofType: null; }; }; }; } }; 'author': { name: 'author'; type: { kind: 'OBJECT'; name: 'Author'; ofType: null; } }; 'category': { name: 'category'; type: { kind: 'OBJECT'; name: 'Category'; ofType: null; } }; 'post': { name: 'post'; type: { kind: 'OBJECT'; name: 'Post'; ofType: null; } }; 'site_settings': { name: 'site_settings'; type: { kind: 'OBJECT'; name: 'SiteSettings'; ofType: null; } }; }; };
    'ResponsiveImage': { kind: 'OBJECT'; name: 'ResponsiveImage'; fields: { 'alt': { name: 'alt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'aspectRatio': { name: 'aspectRatio'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'base64': { name: 'base64'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'bgColor': { name: 'bgColor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'height': { name: 'height'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'sizes': { name: 'sizes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'src': { name: 'src'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'srcSet': { name: 'srcSet'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'webpSrcSet': { name: 'webpSrcSet'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'width': { name: 'width'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'SeoField': { kind: 'OBJECT'; name: 'SeoField'; fields: { 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'image': { name: 'image'; type: { kind: 'OBJECT'; name: 'Asset'; ofType: null; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'twitterCard': { name: 'twitterCard'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'SiteInfo': { kind: 'OBJECT'; name: 'SiteInfo'; fields: { 'locales': { name: 'locales'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; }; };
    'SiteSettings': { kind: 'OBJECT'; name: 'SiteSettings'; fields: { '_createdAt': { name: '_createdAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_firstPublishedAt': { name: '_firstPublishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_modelApiKey': { name: '_modelApiKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; '_publishedAt': { name: '_publishedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_seoMetaTags': { name: '_seoMetaTags'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Tag'; ofType: null; }; }; }; } }; '_status': { name: '_status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; '_updatedAt': { name: '_updatedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'default_seo': { name: 'default_seo'; type: { kind: 'OBJECT'; name: 'SeoField'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'logo': { name: 'logo'; type: { kind: 'OBJECT'; name: 'Asset'; ofType: null; } }; 'site_name': { name: 'site_name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'tagline': { name: 'tagline'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'SiteSettingsFilter': { kind: 'INPUT_OBJECT'; name: 'SiteSettingsFilter'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_status'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: '_createdAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_updatedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_publishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: '_firstPublishedAt'; type: { kind: 'INPUT_OBJECT'; name: 'DateTimeFilter'; ofType: null; }; defaultValue: null }, { name: 'site_name'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'tagline'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'logo'; type: { kind: 'INPUT_OBJECT'; name: 'StringFilter'; ofType: null; }; defaultValue: null }, { name: 'AND'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'SiteSettingsFilter'; ofType: null; }; }; }; defaultValue: null }, { name: 'OR'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'SiteSettingsFilter'; ofType: null; }; }; }; defaultValue: null }]; };
    'SiteSettingsMeta': { kind: 'OBJECT'; name: 'SiteSettingsMeta'; fields: { 'count': { name: 'count'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'SiteSettingsOrderBy': { name: 'SiteSettingsOrderBy'; enumValues: '_createdAt_ASC' | '_createdAt_DESC' | '_updatedAt_ASC' | '_updatedAt_DESC' | '_publishedAt_ASC' | '_publishedAt_DESC' | '_firstPublishedAt_ASC' | '_firstPublishedAt_DESC' | 'site_name_ASC' | 'site_name_DESC' | 'tagline_ASC' | 'tagline_DESC' | 'logo_ASC' | 'logo_DESC'; };
    'String': unknown;
    'StringFilter': { kind: 'INPUT_OBJECT'; name: 'StringFilter'; isOneOf: false; inputFields: [{ name: 'eq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'neq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: 'notIn'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: 'matches'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'matchesObject'; type: { kind: 'INPUT_OBJECT'; name: 'MatchesFilter'; ofType: null; }; defaultValue: null }, { name: 'isBlank'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'isPresent'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'exists'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'StringMultiLocaleField': { kind: 'OBJECT'; name: 'StringMultiLocaleField'; fields: { 'locale': { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'StructuredText': { kind: 'OBJECT'; name: 'StructuredText'; fields: { 'blocks': { name: 'blocks'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; }; }; } }; 'inlineBlocks': { name: 'inlineBlocks'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; }; }; } }; 'links': { name: 'links'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; }; }; } }; 'value': { name: 'value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; } }; }; };
    'Tag': { kind: 'OBJECT'; name: 'Tag'; fields: { 'attributes': { name: 'attributes'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'content': { name: 'content'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: never;
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}