/* Generated by @agent-cms/codegen — DO NOT EDIT. Regenerate from the CMS schema. */
/* eslint-disable */
/* Server-only: do not import from browser code (result-rpc client boundary). */
import type { ErrorDefinitionMap, ProcedureContract, RpcFactory } from "result-rpc";
import {
  createCmsExecutor,
  decodeOutput,
  decodeRecord,
  decodeRecordPage,
  toQueryOptions,
  toRecord,
  type CmsProceduresDeps,
  type RequestActor,
} from "@agent-cms/codegen/server-runtime";
import {
  cmsContract,
  SiteSettingsCodec,
  SITESETTINGS_FIELD_KEYS,
  SiteSettingsVersionCodec,
  SiteSettingsVersionListCodec,
  AuthorCodec,
  AUTHOR_FIELD_KEYS,
  AuthorVersionCodec,
  AuthorVersionListCodec,
  CategoryCodec,
  CATEGORY_FIELD_KEYS,
  CategoryVersionCodec,
  CategoryVersionListCodec,
  PostCodec,
  POST_FIELD_KEYS,
  PostVersionCodec,
  PostVersionListCodec,
  SyncStateCodec,
  AssetListCodec,
  AssetRecordCodec,
  UploadUrlResultCodec,
  AssetCreateResultCodec,
  AssetUpdateResultCodec,
  AssetReplaceResultCodec,
} from "./contract.ts";

/**
 * Server implementations. Spread into the host's own router:
 *   app.router({ ...cmsProcedures(app, contract, { DB: env.DB, actor }), ...hostRouter })
 * where `contract` is the same fragment passed to cmsContract. Handlers run
 * agent-cms's Effect services in-process; `deps.mutationMiddleware` (the host's
 * auth) wraps every mutation, and `deps.actor` records the editor.
 */
export function cmsProcedures<C, MErrors extends ErrorDefinitionMap = ErrorDefinitionMap>(
  app: RpcFactory<C>,
  // The contract is typed WIDE (ErrorDefinitionMap) on purpose: inside a body
  // generic over MErrors the union would be opaque and the concrete cms errors
  // the handlers return would not typecheck. The client's own type safety comes
  // from cmsContract's concrete return, not from this server-side factory.
  contract: ReturnType<typeof cmsContract<C, ErrorDefinitionMap>>,
  deps: CmsProceduresDeps<C, MErrors>,
) {
  const cms = createCmsExecutor(deps);
  const actorFor = (context: C): RequestActor | null => (deps.actor ? deps.actor(context) : null);
  // Wrap a mutation contract with the host's auth middleware when supplied. The
  // middleware's errors (MErrors) are already declared on the contract, so the
  // handler's failure union is unchanged whether or not it is applied.
  const mutation = <TInput, TOutput, TDefs extends ErrorDefinitionMap>(
    procedureContract: ProcedureContract<C, TInput, TOutput, TDefs, "mutation">,
  ) => {
    const impl = app.implement(procedureContract);
    return deps.mutationMiddleware ? impl.use(deps.mutationMiddleware) : impl;
  };
  return {
    siteSettings: {
      get: app.implement(contract.siteSettings.get).handler(async () => {
        const r = await cms.getSingleton("site_settings");
        if (!r.ok) return r;
        return decodeRecord(SiteSettingsCodec, SITESETTINGS_FIELD_KEYS, "siteSettings.get", r.value);
      }),
      update: mutation(contract.siteSettings.update).handler(async ({ input, context }) => {
        const r = await cms.updateSingleton("site_settings", toRecord(input.data), actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(SiteSettingsCodec, SITESETTINGS_FIELD_KEYS, "siteSettings.update", r.value);
      }),
      validate: app.implement(contract.siteSettings.validate).handler(async ({ input }) => cms.validate("site_settings", toRecord(input.data))),
      syncState: app.implement(contract.siteSettings.syncState).handler(async () => {
        const r = await cms.syncStateSingleton("site_settings");
        if (!r.ok) return r;
        return decodeOutput(SyncStateCodec, "siteSettings.syncState", r.value);
      }),
      publish: mutation(contract.siteSettings.publish).handler(async ({ context }) => {
        const r = await cms.publishSingleton("site_settings", actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(SiteSettingsCodec, SITESETTINGS_FIELD_KEYS, "siteSettings.publish", r.value);
      }),
      unpublish: mutation(contract.siteSettings.unpublish).handler(async ({ context }) => {
        const r = await cms.unpublishSingleton("site_settings", actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(SiteSettingsCodec, SITESETTINGS_FIELD_KEYS, "siteSettings.unpublish", r.value);
      }),
    },
    author: {
      list: app.implement(contract.author.list).handler(async ({ input }) => {
        const r = await cms.query("author", toQueryOptions(input));
        if (!r.ok) return r;
        return decodeRecordPage(AuthorCodec, AUTHOR_FIELD_KEYS, "author.list", r.value);
      }),
      byId: app.implement(contract.author.byId).handler(async ({ input }) => {
        const r = await cms.byId("author", input.id);
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.byId", r.value);
      }),
      search: app.implement(contract.author.search).handler(async ({ input }) => cms.search("author", input.q, input.page ?? undefined)),
      create: mutation(contract.author.create).handler(async ({ input, context }) => {
        const r = await cms.create("author", toRecord(input.data), actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.create", r.value);
      }),
      update: mutation(contract.author.update).handler(async ({ input, context }) => {
        const r = await cms.update("author", input.id, toRecord(input.data), actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.update", r.value);
      }),
      delete: mutation(contract.author.delete).handler(async ({ input }) => cms.remove("author", input.id)),
      duplicate: mutation(contract.author.duplicate).handler(async ({ input, context }) => {
        const r = await cms.duplicate("author", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.duplicate", r.value);
      }),
      publish: mutation(contract.author.publish).handler(async ({ input, context }) => {
        const r = await cms.publish("author", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.publish", r.value);
      }),
      unpublish: mutation(contract.author.unpublish).handler(async ({ input, context }) => {
        const r = await cms.unpublish("author", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.unpublish", r.value);
      }),
      publishMany: mutation(contract.author.publishMany).handler(async ({ input, context }) => cms.publishMany("author", input.ids, actorFor(context))),
      unpublishMany: mutation(contract.author.unpublishMany).handler(async ({ input, context }) => cms.unpublishMany("author", input.ids, actorFor(context))),
      deleteMany: mutation(contract.author.deleteMany).handler(async ({ input, context }) => cms.deleteMany("author", input.ids, actorFor(context))),
      links: app.implement(contract.author.links).handler(async ({ input }) => cms.links("author", input.id)),
      validate: app.implement(contract.author.validate).handler(async ({ input }) => cms.validate("author", toRecord(input.data))),
      validateUpdate: app.implement(contract.author.validateUpdate).handler(async ({ input }) => cms.validateUpdate("author", input.id, toRecord(input.data))),
      syncState: app.implement(contract.author.syncState).handler(async ({ input }) => {
        const r = await cms.syncState("author", input.id);
        if (!r.ok) return r;
        return decodeOutput(SyncStateCodec, "author.syncState", r.value);
      }),
      versions: {
        list: app.implement(contract.author.versions.list).handler(async ({ input }) => {
          const r = await cms.versionsList("author", input.id);
          if (!r.ok) return r;
          return decodeOutput(AuthorVersionListCodec, "author.versions.list", r.value);
        }),
        get: app.implement(contract.author.versions.get).handler(async ({ input }) => {
          const r = await cms.versionsGet("author", input.id, input.versionId);
          if (!r.ok) return r;
          return decodeOutput(AuthorVersionCodec, "author.versions.get", r.value);
        }),
        restore: mutation(contract.author.versions.restore).handler(async ({ input, context }) => {
          const r = await cms.versionsRestore("author", input.id, input.versionId, actorFor(context));
          if (!r.ok) return r;
          return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.versions.restore", r.value);
        }),
      },
      schedulePublish: mutation(contract.author.schedulePublish).handler(async ({ input, context }) => {
        const r = await cms.schedulePublish("author", input.id, input.at, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.schedulePublish", r.value);
      }),
      scheduleUnpublish: mutation(contract.author.scheduleUnpublish).handler(async ({ input, context }) => {
        const r = await cms.scheduleUnpublish("author", input.id, input.at, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.scheduleUnpublish", r.value);
      }),
      clearSchedule: mutation(contract.author.clearSchedule).handler(async ({ input, context }) => {
        const r = await cms.clearSchedule("author", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.clearSchedule", r.value);
      }),
    },
    category: {
      list: app.implement(contract.category.list).handler(async ({ input }) => {
        const r = await cms.query("category", toQueryOptions(input));
        if (!r.ok) return r;
        return decodeRecordPage(CategoryCodec, CATEGORY_FIELD_KEYS, "category.list", r.value);
      }),
      byId: app.implement(contract.category.byId).handler(async ({ input }) => {
        const r = await cms.byId("category", input.id);
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.byId", r.value);
      }),
      search: app.implement(contract.category.search).handler(async ({ input }) => cms.search("category", input.q, input.page ?? undefined)),
      create: mutation(contract.category.create).handler(async ({ input, context }) => {
        const r = await cms.create("category", toRecord(input.data), actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.create", r.value);
      }),
      update: mutation(contract.category.update).handler(async ({ input, context }) => {
        const r = await cms.update("category", input.id, toRecord(input.data), actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.update", r.value);
      }),
      delete: mutation(contract.category.delete).handler(async ({ input }) => cms.remove("category", input.id)),
      duplicate: mutation(contract.category.duplicate).handler(async ({ input, context }) => {
        const r = await cms.duplicate("category", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.duplicate", r.value);
      }),
      publish: mutation(contract.category.publish).handler(async ({ input, context }) => {
        const r = await cms.publish("category", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.publish", r.value);
      }),
      unpublish: mutation(contract.category.unpublish).handler(async ({ input, context }) => {
        const r = await cms.unpublish("category", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.unpublish", r.value);
      }),
      publishMany: mutation(contract.category.publishMany).handler(async ({ input, context }) => cms.publishMany("category", input.ids, actorFor(context))),
      unpublishMany: mutation(contract.category.unpublishMany).handler(async ({ input, context }) => cms.unpublishMany("category", input.ids, actorFor(context))),
      deleteMany: mutation(contract.category.deleteMany).handler(async ({ input, context }) => cms.deleteMany("category", input.ids, actorFor(context))),
      links: app.implement(contract.category.links).handler(async ({ input }) => cms.links("category", input.id)),
      validate: app.implement(contract.category.validate).handler(async ({ input }) => cms.validate("category", toRecord(input.data))),
      validateUpdate: app.implement(contract.category.validateUpdate).handler(async ({ input }) => cms.validateUpdate("category", input.id, toRecord(input.data))),
      syncState: app.implement(contract.category.syncState).handler(async ({ input }) => {
        const r = await cms.syncState("category", input.id);
        if (!r.ok) return r;
        return decodeOutput(SyncStateCodec, "category.syncState", r.value);
      }),
      versions: {
        list: app.implement(contract.category.versions.list).handler(async ({ input }) => {
          const r = await cms.versionsList("category", input.id);
          if (!r.ok) return r;
          return decodeOutput(CategoryVersionListCodec, "category.versions.list", r.value);
        }),
        get: app.implement(contract.category.versions.get).handler(async ({ input }) => {
          const r = await cms.versionsGet("category", input.id, input.versionId);
          if (!r.ok) return r;
          return decodeOutput(CategoryVersionCodec, "category.versions.get", r.value);
        }),
        restore: mutation(contract.category.versions.restore).handler(async ({ input, context }) => {
          const r = await cms.versionsRestore("category", input.id, input.versionId, actorFor(context));
          if (!r.ok) return r;
          return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.versions.restore", r.value);
        }),
      },
      schedulePublish: mutation(contract.category.schedulePublish).handler(async ({ input, context }) => {
        const r = await cms.schedulePublish("category", input.id, input.at, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.schedulePublish", r.value);
      }),
      scheduleUnpublish: mutation(contract.category.scheduleUnpublish).handler(async ({ input, context }) => {
        const r = await cms.scheduleUnpublish("category", input.id, input.at, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.scheduleUnpublish", r.value);
      }),
      clearSchedule: mutation(contract.category.clearSchedule).handler(async ({ input, context }) => {
        const r = await cms.clearSchedule("category", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(CategoryCodec, CATEGORY_FIELD_KEYS, "category.clearSchedule", r.value);
      }),
    },
    post: {
      list: app.implement(contract.post.list).handler(async ({ input }) => {
        const r = await cms.query("post", toQueryOptions(input));
        if (!r.ok) return r;
        return decodeRecordPage(PostCodec, POST_FIELD_KEYS, "post.list", r.value);
      }),
      byId: app.implement(contract.post.byId).handler(async ({ input }) => {
        const r = await cms.byId("post", input.id);
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.byId", r.value);
      }),
      search: app.implement(contract.post.search).handler(async ({ input }) => cms.search("post", input.q, input.page ?? undefined)),
      create: mutation(contract.post.create).handler(async ({ input, context }) => {
        const r = await cms.create("post", toRecord(input.data), actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.create", r.value);
      }),
      update: mutation(contract.post.update).handler(async ({ input, context }) => {
        const r = await cms.update("post", input.id, toRecord(input.data), actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.update", r.value);
      }),
      delete: mutation(contract.post.delete).handler(async ({ input }) => cms.remove("post", input.id)),
      duplicate: mutation(contract.post.duplicate).handler(async ({ input, context }) => {
        const r = await cms.duplicate("post", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.duplicate", r.value);
      }),
      publish: mutation(contract.post.publish).handler(async ({ input, context }) => {
        const r = await cms.publish("post", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.publish", r.value);
      }),
      unpublish: mutation(contract.post.unpublish).handler(async ({ input, context }) => {
        const r = await cms.unpublish("post", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.unpublish", r.value);
      }),
      publishMany: mutation(contract.post.publishMany).handler(async ({ input, context }) => cms.publishMany("post", input.ids, actorFor(context))),
      unpublishMany: mutation(contract.post.unpublishMany).handler(async ({ input, context }) => cms.unpublishMany("post", input.ids, actorFor(context))),
      deleteMany: mutation(contract.post.deleteMany).handler(async ({ input, context }) => cms.deleteMany("post", input.ids, actorFor(context))),
      links: app.implement(contract.post.links).handler(async ({ input }) => cms.links("post", input.id)),
      validate: app.implement(contract.post.validate).handler(async ({ input }) => cms.validate("post", toRecord(input.data))),
      validateUpdate: app.implement(contract.post.validateUpdate).handler(async ({ input }) => cms.validateUpdate("post", input.id, toRecord(input.data))),
      syncState: app.implement(contract.post.syncState).handler(async ({ input }) => {
        const r = await cms.syncState("post", input.id);
        if (!r.ok) return r;
        return decodeOutput(SyncStateCodec, "post.syncState", r.value);
      }),
      versions: {
        list: app.implement(contract.post.versions.list).handler(async ({ input }) => {
          const r = await cms.versionsList("post", input.id);
          if (!r.ok) return r;
          return decodeOutput(PostVersionListCodec, "post.versions.list", r.value);
        }),
        get: app.implement(contract.post.versions.get).handler(async ({ input }) => {
          const r = await cms.versionsGet("post", input.id, input.versionId);
          if (!r.ok) return r;
          return decodeOutput(PostVersionCodec, "post.versions.get", r.value);
        }),
        restore: mutation(contract.post.versions.restore).handler(async ({ input, context }) => {
          const r = await cms.versionsRestore("post", input.id, input.versionId, actorFor(context));
          if (!r.ok) return r;
          return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.versions.restore", r.value);
        }),
      },
      schedulePublish: mutation(contract.post.schedulePublish).handler(async ({ input, context }) => {
        const r = await cms.schedulePublish("post", input.id, input.at, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.schedulePublish", r.value);
      }),
      scheduleUnpublish: mutation(contract.post.scheduleUnpublish).handler(async ({ input, context }) => {
        const r = await cms.scheduleUnpublish("post", input.id, input.at, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.scheduleUnpublish", r.value);
      }),
      clearSchedule: mutation(contract.post.clearSchedule).handler(async ({ input, context }) => {
        const r = await cms.clearSchedule("post", input.id, actorFor(context));
        if (!r.ok) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.clearSchedule", r.value);
      }),
    },
    assets: {
      list: app.implement(contract.assets.list).handler(async ({ input }) => {
        const r = await cms.assetsList({ query: input.q ?? undefined, page: input.page ?? undefined, orderBy: input.orderBy ? [...input.orderBy] : undefined });
        if (!r.ok) return r;
        return decodeOutput(AssetListCodec, "assets.list", r.value);
      }),
      get: app.implement(contract.assets.get).handler(async ({ input }) => {
        const r = await cms.assetsGet(input.id);
        if (!r.ok) return r;
        return decodeOutput(AssetRecordCodec, "assets.get", r.value);
      }),
      createUploadUrl: mutation(contract.assets.createUploadUrl).handler(async ({ input }) => {
        const r = await cms.assetsCreateUploadUrl({ filename: input.filename, mimeType: input.contentType });
        if (!r.ok) return r;
        return decodeOutput(UploadUrlResultCodec, "assets.createUploadUrl", r.value);
      }),
      create: mutation(contract.assets.create).handler(async ({ input, context }) => {
        const r = await cms.assetsCreate(input.data, actorFor(context));
        if (!r.ok) return r;
        return decodeOutput(AssetCreateResultCodec, "assets.create", r.value);
      }),
      importFromUrl: mutation(contract.assets.importFromUrl).handler(async ({ input, context }) => {
        const r = await cms.assetsImportFromUrl(input, actorFor(context));
        if (!r.ok) return r;
        return decodeOutput(AssetCreateResultCodec, "assets.importFromUrl", r.value);
      }),
      update: mutation(contract.assets.update).handler(async ({ input, context }) => {
        const r = await cms.assetsUpdate(input.id, input.data, actorFor(context));
        if (!r.ok) return r;
        return decodeOutput(AssetUpdateResultCodec, "assets.update", r.value);
      }),
      replace: mutation(contract.assets.replace).handler(async ({ input, context }) => {
        const r = await cms.assetsReplace(input.id, input.data, actorFor(context));
        if (!r.ok) return r;
        return decodeOutput(AssetReplaceResultCodec, "assets.replace", r.value);
      }),
      delete: mutation(contract.assets.delete).handler(async ({ input }) => cms.assetsDelete(input.id, input.force ?? false)),
      usages: app.implement(contract.assets.usages).handler(async ({ input }) => cms.assetsUsages(input.id)),
    },
  };
}
