/* Generated by @agent-cms/codegen — DO NOT EDIT. Regenerate from the CMS schema. */
/* eslint-disable */
import { pickErrors, wire, type ContractFactory, type ErrorDefinitionMap, type InputOf } from "result-rpc";
import * as guard from "@agent-cms/codegen/guards";
import { cmsErrors } from "@agent-cms/codegen/errors";
import { mutationErrors } from "./host-errors.js";
import type {
  BlockLevelNode as DastBlockLevelNode,
  BlockNode as DastBlockRefNode,
  BlockquoteNode as DastBlockquoteNode,
  CodeNode as DastCodeNode,
  CustomMark as DastCustomMark,
  DastDocument,
  DefaultMark as DastDefaultMark,
  HeadingNode as DastHeadingNode,
  InlineBlockNode as DastInlineBlockNode,
  InlineItemNode as DastInlineItemNode,
  InlineNode as DastInlineNode,
  ItemLinkNode as DastItemLinkNode,
  LinkNode as DastLinkNode,
  ListItemNode as DastListItemNode,
  ListNode as DastListNode,
  Mark as DastMark,
  ParagraphNode as DastParagraphNode,
  RootNode as DastRootNode,
  SpanNode as DastSpanNode,
  TableCellNode as DastTableCellNode,
  TableNode as DastTableNode,
  TableRowNode as DastTableRowNode,
  ThematicBreakNode as DastThematicBreakNode,
} from "@agent-cms/dast";


export type Locale = string;
/** Localized fields travel as locale-keyed maps. */
export type Localized<T> = Partial<Record<Locale, T>>;

// --- DAST (shared with the CMS and the editor) ---
// Re-exported under the historical `Dast*` names so consumers can keep
// importing them from this contract. The underlying import above is types-only
// and therefore erased at build time: the contract stays browser-safe and
// pulls in nothing from the CMS runtime. `@agent-cms/dast` has zero runtime
// dependencies — add it to the host's dependencies.
export type {
  DastBlockLevelNode,
  DastBlockRefNode,
  DastBlockquoteNode,
  DastCodeNode,
  DastCustomMark,
  DastDocument,
  DastDefaultMark,
  DastHeadingNode,
  DastInlineBlockNode,
  DastInlineItemNode,
  DastInlineNode,
  DastItemLinkNode,
  DastLinkNode,
  DastListItemNode,
  DastListNode,
  DastMark,
  DastParagraphNode,
  DastRootNode,
  DastSpanNode,
  DastTableCellNode,
  DastTableNode,
  DastTableRowNode,
  DastThematicBreakNode,
};

// --- Shared value types (structurally identical to agent-cms's own) ---

/**
 * Write shape of a media reference: an asset id, or an upload descriptor.
 * The read-only keys a read adds (`url`, `filename`, …) are declared optional
 * so a value read off a record can be written straight back — the CMS strips
 * them before storing (read-modify-write is lossless).
 */
export type MediaValue =
  | string
  | {
      upload_id: string;
      alt?: string | null;
      title?: string | null;
      focal_point?: { x: number; y: number } | null;
      custom_data?: Record<string, unknown> | null;
      url?: string;
      filename?: string;
      mime_type?: string;
      size?: number;
      width?: number | null;
      height?: number | null;
      blurhash?: string | null;
    };

/**
 * Read shape of a media reference: the stored reference merged with the asset
 * it points at, including the canonical absolute `url`. Assignable to
 * `MediaValue`, so reads can be edited and written back.
 *
 * Compose transforms with `assetUrl(value, { width })` from
 * `@agent-cms/codegen/assets` (Cloudflare Image Resizing).
 */
export interface MediaRead {
  upload_id: string;
  url: string;
  filename: string;
  mime_type: string;
  size: number;
  width: number | null;
  height: number | null;
  alt: string | null;
  title: string | null;
  focal_point: { x: number; y: number } | null;
  custom_data: Record<string, unknown> | null;
  blurhash: string | null;
}

export interface SeoValue {
  title?: string;
  description?: string;
  image?: string;
  twitterCard?: string;
  /** Read-only: the canonical URL of `image`, resolved by the CMS. */
  image_url?: string | null;
}

/**
 * Write shape for structured_text: the DAST value plus (optionally) new/updated
 * block payloads.
 *
 * `TBlock` defaults to a raw payload object, and every per-field write alias
 * widens it to `<the field's block union> | Record<string, unknown>` so a value
 * read back off a record (whose blocks are the concrete generated interfaces)
 * is assignable straight into an update — read-modify-write compiles with no
 * adapter.
 */
export interface StructuredTextWrite<TBlock = Record<string, unknown>> {
  value: DastDocument;
  blocks?: Readonly<Record<string, TBlock>>;
}

// --- Filter operator vocabulary (mirrors src/graphql/filter-compiler.ts) ---
// A per-model `${Model}Filter` is carried as wire.serializable<...>() and the
// server re-validates every filter in RecordService.queryRecords. Codegen ships
// the TS shape for authoring ergonomics, NOT a full nested AND/OR wire-codec
// algebra — that round-trips losslessly through the serializer and gains nothing
// from a hand-rolled recursive codec.

export interface StringFilter<T extends string = string> {
  eq?: T; neq?: T; in?: readonly T[]; notIn?: readonly T[];
  matches?: string | { pattern: string; caseSensitive?: boolean };
  notMatches?: string | { pattern: string; caseSensitive?: boolean };
  isBlank?: boolean; isPresent?: boolean; exists?: boolean;
}
export interface NumberFilter {
  eq?: number; neq?: number; gt?: number; lt?: number; gte?: number; lte?: number;
  in?: readonly number[]; notIn?: readonly number[]; exists?: boolean;
}
export interface DateFilter {
  eq?: string; neq?: string; gt?: string; lt?: string; gte?: string; lte?: string; exists?: boolean;
}
export interface BooleanFilter { eq?: boolean; neq?: boolean; exists?: boolean; }
export interface LinkFilter { eq?: string; neq?: string; in?: readonly string[]; notIn?: readonly string[]; exists?: boolean; }
export interface LinksFilter { eq?: readonly string[]; allIn?: readonly string[]; anyIn?: readonly string[]; notIn?: readonly string[]; exists?: boolean; }
export interface MediaFilter { eq?: string; neq?: string; in?: readonly string[]; notIn?: readonly string[]; exists?: boolean; }
export interface GalleryFilter { allIn?: readonly string[]; anyIn?: readonly string[]; notIn?: readonly string[]; exists?: boolean; }
export interface GeoFilter { near?: { latitude: number; longitude: number; radius: number }; exists?: boolean; }
export type RecordStatus = "draft" | "published" | "updated";
export interface StatusFilter { eq?: RecordStatus; neq?: RecordStatus; in?: readonly RecordStatus[]; notIn?: readonly RecordStatus[]; exists?: boolean; }
export interface LocalesFilter { allIn?: readonly Locale[]; anyIn?: readonly Locale[]; notIn?: readonly Locale[]; }

/** Sidebar status cluster (RecordService.getSyncState). */
export interface RecordSyncState {
  status: string | null;
  publishedAt: string | null;
  firstPublishedAt: string | null;
  scheduledPublishAt: string | null;
  scheduledUnpublishAt: string | null;
  changedFields: string[];
}

/** A backlink: a record referencing this one via a link/links field. */
export interface RecordBacklink { modelApiKey: string; recordId: string; fieldApiKey: string; }

/** Picker-search presentation row. */
export interface PickerRow { id: string; title: string | null; image: string | null; imageUrl: string | null; status: string | null; updatedAt: string | null; }

// --- Presentation hints (ADR 0006) ---

/**
 * Which of a model's fields title and illustrate a row. Emitted per model as
 * `<MODEL>_PRESENTATION` with the guess resolved AT GENERATION TIME, so the
 * fallback is deterministic and visible in this artifact:
 *
 * - `title`: the model's `title_field` hint → else a field named
 *   title/name/heading/label → else the first required string/text/slug field →
 *   else the first string/text/slug field → else `null` ("no title field —
 *   use the record id", which is what picker rows do).
 * - `image`: the model's `image_preview_field` hint → else the first `media`
 *   field → else `null`.
 */
export interface ModelPresentation {
  /** The model's api_key. */
  readonly model: string;
  /** Field api_key whose value titles a row, or null (fall back to the id). */
  readonly title: string | null;
  /** Field api_key holding the row's preview image, or null. */
  readonly image: string | null;
}

/** The media-ish shape presentRecord can pull a preview out of. */
function presentationMedia(value: unknown): { uploadId: string; url: string | null } | null {
  if (Array.isArray(value)) {
    for (const entry of value) {
      const first = presentationMedia(entry);
      if (first) return first;
    }
    return null;
  }
  if (typeof value === "string") return value.length > 0 ? { uploadId: value, url: null } : null;
  if (typeof value !== "object" || value === null) return null;
  const uploadId = Reflect.get(value, "upload_id");
  if (typeof uploadId !== "string") return null;
  const url = Reflect.get(value, "url");
  return { uploadId, url: typeof url === "string" ? url : null };
}

/**
 * Render any record as the row shape the `search` procedure returns, using the
 * model's presentation descriptor — so a list view, a picker and a link chip
 * can share one row component:
 *
 *   presentRecord(post, POST_PRESENTATION)  // → { id, title, image, imageUrl, … }
 *
 * Same semantics as server-side picker rows: `title` falls back to the record
 * id when the model has no title field, `image` is the asset id and
 * `imageUrl` its canonical URL (null until the record round-trips through a
 * read). Localized fields carry locale maps — pick a locale before presenting.
 */
export function presentRecord<T extends { id: string }>(
  record: T,
  presentation: ModelPresentation,
): PickerRow {
  const rawTitle = presentation.title === null ? null : Reflect.get(record, presentation.title);
  const media = presentation.image === null ? null : presentationMedia(Reflect.get(record, presentation.image));
  const status = Reflect.get(record, "status");
  const updatedAt = Reflect.get(record, "updatedAt");
  return {
    id: record.id,
    title:
      presentation.title === null
        ? record.id
        : typeof rawTitle === "string" && rawTitle.length > 0
          ? rawTitle
          : null,
    image: media === null ? null : media.uploadId,
    imageUrl: media === null ? null : media.url,
    status: typeof status === "string" ? status : null,
    updatedAt: typeof updatedAt === "string" ? updatedAt : null,
  };
}

/** Per-id result of a bulk publish/unpublish/delete (data, never a top-level failure). */
export interface BulkResult { id: string; ok: boolean; error?: string; }

/** A stored version. `snapshot` holds the record's own field values (partial). */
export interface VersionOf<T> {
  id: string;
  model_api_key: string;
  record_id: string;
  version_number: number;
  action: string;
  actor_type: string | null;
  actor_label: string | null;
  actor_token_id: string | null;
  created_at: string;
  snapshot: Partial<T>;
}

// --- Assets (shared namespace) ---

/** Asset row as stored (snake_case; colors/focal_point/tags are JSON strings). */
export interface AssetRecord {
  id: string; filename: string; basename: string | null; format: string | null;
  mime_type: string; size: number; width: number | null; height: number | null;
  alt: string | null; title: string | null; r2_key: string; blurhash: string | null;
  /** Canonical absolute URL (ASSET_BASE_URL, else the CMS's own /assets route). */
  url: string;
  colors: string | null; focal_point: string | null; tags: string; custom_data: string | null;
  created_at: string; updated_at: string; created_by: string | null; updated_by: string | null;
}
export interface AssetCreateInput {
  id?: string; filename: string; mimeType: string; size?: number;
  width?: number; height?: number; alt?: string; title?: string; r2Key?: string;
  blurhash?: string; colors?: readonly string[]; focalPoint?: { x: number; y: number }; tags?: readonly string[];
}
export interface AssetImportInput {
  id?: string; url: string; filename?: string; mimeType?: string;
  width?: number; height?: number; alt?: string; title?: string; r2Key?: string;
  blurhash?: string; colors?: readonly string[]; focalPoint?: { x: number; y: number }; tags?: readonly string[];
}
export interface AssetUpdateInput { alt?: string; title?: string; width?: number; height?: number; }
export interface AssetUsage { modelApiKey: string; recordId: string; fieldApiKey: string; }
export interface AssetCreateResult {
  id: string; filename: string; mimeType: string; size: number;
  width?: number; height?: number; alt?: string; title?: string; r2Key: string; url: string;
  createdAt: string; updatedAt: string; createdBy: string | null; updatedBy: string | null;
}
export interface AssetReplaceResult {
  id: string; filename: string; mimeType: string; size: number;
  width?: number; height?: number; alt: string | null; title: string | null;
  r2Key: string; url: string; replaced: true; updatedAt: string; updatedBy: string | null;
}
export interface AssetUpdateResult { id: string; alt: string | null; title: string | null; width: number | null; height: number | null; url: string; updatedAt: string; updatedBy: string | null; }
export interface UploadUrlResult { uploadUrl: string; r2Key: string; assetId: string; }

// --- Shared reusable codecs (defined once, referenced by every model) ---
const nullableString = wire.union([wire.string, wire.null] as const);
const PageInput = wire.object({ limit: wire.optional(wire.integer()), offset: wire.optional(wire.integer()) });
const StatusInput = wire.union([wire.literal("draft"), wire.literal("published"), wire.literal("updated")] as const);
const IdInput = wire.object({ id: wire.string });
const IdsInput = wire.object({ ids: wire.array(wire.string) });
export const PickerRowsCodec = wire.array(wire.object({
  id: wire.string, title: nullableString, image: nullableString, imageUrl: nullableString,
  status: nullableString, updatedAt: nullableString,
}));
export const BulkResultsCodec = wire.array(wire.object({ id: wire.string, ok: wire.boolean, error: wire.optional(wire.string) }));
export const BacklinksCodec = wire.array(wire.object({ modelApiKey: wire.string, recordId: wire.string, fieldApiKey: wire.string }));
export const ValidCodec = wire.object({ valid: wire.boolean });
export const SyncStateCodec = wire.object({
  status: nullableString, publishedAt: nullableString, firstPublishedAt: nullableString,
  scheduledPublishAt: nullableString, scheduledUnpublishAt: nullableString, changedFields: wire.array(wire.string),
});
export const AssetRecordCodec = wire.serializable<AssetRecord>(guard.isAssetRecord, { id: "agent-cms/AssetRecord@1" });
export const AssetListCodec = wire.object({ assets: wire.array(AssetRecordCodec), total: wire.integer() });
export const AssetUsagesCodec = wire.array(wire.object({ modelApiKey: wire.string, recordId: wire.string, fieldApiKey: wire.string }));
export const AssetCreateResultCodec = wire.serializable<AssetCreateResult>(guard.isAssetCreateResult, { id: "agent-cms/AssetCreateResult@1" });
export const AssetReplaceResultCodec = wire.serializable<AssetReplaceResult>(guard.isAssetReplaceResult, { id: "agent-cms/AssetReplaceResult@1" });
export const AssetUpdateResultCodec = wire.serializable<AssetUpdateResult>(guard.isAssetUpdateResult, { id: "agent-cms/AssetUpdateResult@1" });
export const UploadUrlResultCodec = wire.serializable<UploadUrlResult>(guard.isUploadUrlResult, { id: "agent-cms/UploadUrlResult@1" });
export const AssetDeletedCodec = wire.object({ deleted: wire.boolean });

/** Block model "Hero Section" (hero_section) */
export interface HeroSectionBlock {
  id: string;
  _type: "hero_section";
  headline: string;
  subheadline?: string;
  background_image?: MediaRead;
  cta_text?: string;
  cta_url?: string;
  author?: string;
}

/** Block model "Code Block" (code_block) */
export interface CodeBlockBlock {
  id: string;
  _type: "code_block";
  code: string;
  language?: string;
  filename?: string;
}

/** Block model "Image Gallery" (image_gallery) */
export interface ImageGalleryBlock {
  id: string;
  _type: "image_gallery";
  images?: MediaRead[];
  caption?: string;
  layout?: string;
}

/** Block model "Feature Card" (feature_card) */
export interface FeatureCardBlock {
  id: string;
  _type: "feature_card";
  title: string;
  description?: string;
  details?: { value: DastDocument; blocks: Record<string, unknown> };
}

/** Block model "Feature Grid" (feature_grid) */
export interface FeatureGridBlock {
  id: string;
  _type: "feature_grid";
  heading: string;
  features?: { value: DastDocument; blocks: Record<string, unknown> };
}

// --- Presentation descriptors (ADR 0006; fallbacks resolved at generation time) ---

/** Presentation for post: title = generation-time fallback, image = no candidate. */
export const POST_PRESENTATION = {
  model: "post",
  title: "title",
  image: null,
} as const satisfies ModelPresentation;

/** Presentation for author: title = generation-time fallback, image = generation-time fallback. */
export const AUTHOR_PRESENTATION = {
  model: "author",
  title: "name",
  image: "avatar",
} as const satisfies ModelPresentation;

/** Presentation for hero_section: title = generation-time fallback, image = generation-time fallback. */
export const HEROSECTION_PRESENTATION = {
  model: "hero_section",
  title: "headline",
  image: "background_image",
} as const satisfies ModelPresentation;

/** Presentation for code_block: title = generation-time fallback, image = no candidate. */
export const CODEBLOCK_PRESENTATION = {
  model: "code_block",
  title: "code",
  image: null,
} as const satisfies ModelPresentation;

/** Presentation for image_gallery: title = generation-time fallback, image = no candidate. */
export const IMAGEGALLERY_PRESENTATION = {
  model: "image_gallery",
  title: "caption",
  image: null,
} as const satisfies ModelPresentation;

/** Presentation for feature_card: title = generation-time fallback, image = no candidate. */
export const FEATURECARD_PRESENTATION = {
  model: "feature_card",
  title: "title",
  image: null,
} as const satisfies ModelPresentation;

/** Presentation for feature_grid: title = generation-time fallback, image = no candidate. */
export const FEATUREGRID_PRESENTATION = {
  model: "feature_grid",
  title: "heading",
  image: null,
} as const satisfies ModelPresentation;

/** Every model's presentation descriptor, keyed by api_key. */
export const PRESENTATION = {
  "post": POST_PRESENTATION,
  "author": AUTHOR_PRESENTATION,
  "hero_section": HEROSECTION_PRESENTATION,
  "code_block": CODEBLOCK_PRESENTATION,
  "image_gallery": IMAGEGALLERY_PRESENTATION,
  "feature_card": FEATURECARD_PRESENTATION,
  "feature_grid": FEATUREGRID_PRESENTATION,
} as const satisfies Record<string, ModelPresentation>;

/** structured_text envelope for post.content */
export interface PostContentEnvelope {
  value: DastDocument;
  blocks: Record<string, HeroSectionBlock | CodeBlockBlock | ImageGalleryBlock | FeatureCardBlock | FeatureGridBlock>;
}

/** Write shape for post.content. PostContentEnvelope (what a read returns) is assignable to it. */
export type PostContentWrite = StructuredTextWrite<HeroSectionBlock | CodeBlockBlock | ImageGalleryBlock | FeatureCardBlock | FeatureGridBlock | Record<string, unknown>>;

/** Post (post) */
export const PostCodec = wire.object({
  id: wire.string,
  status: wire.string,
  createdAt: wire.union([wire.string, wire.null] as const),
  updatedAt: wire.union([wire.string, wire.null] as const),
  publishedAt: wire.union([wire.string, wire.null] as const),
  title: wire.string,
  slug: wire.union([wire.string, wire.null] as const),
  excerpt: wire.union([wire.string, wire.null] as const),
  content: wire.union([wire.serializable<PostContentEnvelope>(guard.isStructuredTextEnvelope, { id: "agent-cms/st.post.content.read@fa5c8fd2" }), wire.null] as const),
});
export type Post = InputOf<typeof PostCodec>;

export const PostCreateInput = wire.object({
  title: wire.string,
  slug: wire.optional(wire.string),
  excerpt: wire.optional(wire.string),
  content: wire.optional(wire.serializable<PostContentWrite>(guard.isStructuredTextWrite, { id: "agent-cms/st.post.content.write@fa5c8fd2" })),
});
export type CreatePost = InputOf<typeof PostCreateInput>;

export const PostUpdateInput = wire.object({
  title: wire.optional(wire.union([wire.string, wire.null] as const)),
  slug: wire.optional(wire.union([wire.string, wire.null] as const)),
  excerpt: wire.optional(wire.union([wire.string, wire.null] as const)),
  content: wire.optional(wire.union([wire.serializable<PostContentWrite>(guard.isStructuredTextWrite, { id: "agent-cms/st.post.content.write@fa5c8fd2" }), wire.null] as const)),
});
export type UpdatePost = InputOf<typeof PostUpdateInput>;

export const POST_FIELD_KEYS = ["title", "slug", "excerpt", "content"] as const;

export const PostVersionCodec = wire.serializable<VersionOf<Post>>(guard.isVersionOf, { id: "agent-cms/version.post@1" });
export const PostVersionListCodec = wire.array(PostVersionCodec);

export interface PostFilter {
  id?: StringFilter;
  title?: StringFilter;
  slug?: StringFilter;
  excerpt?: StringFilter;
  _status?: StatusFilter;
  _createdAt?: DateFilter;
  _updatedAt?: DateFilter;
  _publishedAt?: DateFilter;
  _firstPublishedAt?: DateFilter;
  _position?: NumberFilter;
  AND?: readonly PostFilter[];
  OR?: readonly PostFilter[];
}

export type PostOrderBy = "title_ASC" | "title_DESC" | "slug_ASC" | "slug_DESC" | "excerpt_ASC" | "excerpt_DESC" | "id_ASC" | "id_DESC" | "_status_ASC" | "_status_DESC" | "_position_ASC" | "_position_DESC" | "_createdAt_ASC" | "_createdAt_DESC" | "_updatedAt_ASC" | "_updatedAt_DESC" | "_publishedAt_ASC" | "_publishedAt_DESC" | "_firstPublishedAt_ASC" | "_firstPublishedAt_DESC";

/** Author (author) */
export const AuthorCodec = wire.object({
  id: wire.string,
  status: wire.string,
  createdAt: wire.union([wire.string, wire.null] as const),
  updatedAt: wire.union([wire.string, wire.null] as const),
  publishedAt: wire.union([wire.string, wire.null] as const),
  name: wire.string,
  role: wire.union([wire.string, wire.null] as const),
  avatar: wire.union([wire.serializable<MediaRead>(guard.isMediaRead, { id: "agent-cms/media.read@1" }), wire.null] as const), // read: asset + canonical url · write: asset id or descriptor
});
export type Author = InputOf<typeof AuthorCodec>;

export const AuthorCreateInput = wire.object({
  name: wire.string,
  role: wire.optional(wire.string),
  avatar: wire.optional(wire.serializable<MediaValue>(guard.isMediaValue, { id: "agent-cms/media.write@1" })),
});
export type CreateAuthor = InputOf<typeof AuthorCreateInput>;

export const AuthorUpdateInput = wire.object({
  name: wire.optional(wire.union([wire.string, wire.null] as const)),
  role: wire.optional(wire.union([wire.string, wire.null] as const)),
  avatar: wire.optional(wire.union([wire.serializable<MediaValue>(guard.isMediaValue, { id: "agent-cms/media.write@1" }), wire.null] as const)),
});
export type UpdateAuthor = InputOf<typeof AuthorUpdateInput>;

export const AUTHOR_FIELD_KEYS = ["name", "role", "avatar"] as const;

export const AuthorVersionCodec = wire.serializable<VersionOf<Author>>(guard.isVersionOf, { id: "agent-cms/version.author@1" });
export const AuthorVersionListCodec = wire.array(AuthorVersionCodec);

export interface AuthorFilter {
  id?: StringFilter;
  name?: StringFilter;
  role?: StringFilter;
  avatar?: MediaFilter;
  _status?: StatusFilter;
  _createdAt?: DateFilter;
  _updatedAt?: DateFilter;
  _publishedAt?: DateFilter;
  _firstPublishedAt?: DateFilter;
  _position?: NumberFilter;
  AND?: readonly AuthorFilter[];
  OR?: readonly AuthorFilter[];
}

export type AuthorOrderBy = "name_ASC" | "name_DESC" | "role_ASC" | "role_DESC" | "id_ASC" | "id_DESC" | "_status_ASC" | "_status_DESC" | "_position_ASC" | "_position_DESC" | "_createdAt_ASC" | "_createdAt_DESC" | "_updatedAt_ASC" | "_updatedAt_DESC" | "_publishedAt_ASC" | "_publishedAt_DESC" | "_firstPublishedAt_ASC" | "_firstPublishedAt_DESC";

/**
 * Contract fragment. Spread into the host's own contract:
 *   app.contract({ ...cmsContract(app), ...hostProcedures })
 * The errors your mutation middleware contributes are declared on every CMS
 * mutation, read from ./host-errors.ts — result-rpc is contract-first, so a
 * middleware error that is not declared there is rejected.
 */
export function cmsContract<C>(app: ContractFactory<C>) {
    const postList = app.procedure().input(wire.object({
      filter: wire.optional(wire.serializable<PostFilter>(guard.isFilter, { id: "agent-cms/filter.post@1" })),
      orderBy: wire.optional(wire.array(wire.serializable<PostOrderBy>(guard.isOrderBy, { id: "agent-cms/order-by.post@1" }))),
      page: wire.optional(PageInput),
      status: wire.optional(StatusInput),
    })).output(wire.object({ records: wire.array(PostCodec), total: wire.integer() }))
      .errors(pickErrors(cmsErrors, "schemaDrift")).query();
    const post = {
      list: postList,
      byId: app.procedure().input(IdInput).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
      search: app.procedure().input(wire.object({ q: wire.string, page: wire.optional(PageInput) })).output(PickerRowsCodec)
        .errors(pickErrors(cmsErrors, "schemaDrift")).query(),
      create: app.procedure().input(wire.object({ data: PostCreateInput })).output(PostCodec)
        .errors(pickErrors(cmsErrors, "validationFailed", "duplicate", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      update: app.procedure().input(wire.object({ id: wire.string, data: PostUpdateInput })).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "duplicate", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      delete: app.procedure().input(IdInput).output(wire.object({ id: wire.string }))
        .errors(pickErrors(cmsErrors, "recordNotFound", "referenceConflict", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      duplicate: app.procedure().input(IdInput).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      publish: app.procedure().input(IdInput).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      unpublish: app.procedure().input(IdInput).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      publishMany: app.procedure().input(IdsInput).output(BulkResultsCodec).errors(mutationErrors).affects(postList).mutation(),
      unpublishMany: app.procedure().input(IdsInput).output(BulkResultsCodec).errors(mutationErrors).affects(postList).mutation(),
      deleteMany: app.procedure().input(IdsInput).output(BulkResultsCodec).errors(mutationErrors).affects(postList).mutation(),
      links: app.procedure().input(IdInput).output(BacklinksCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
      validate: app.procedure().input(wire.object({ data: wire.serializable<Partial<CreatePost>>(guard.isRecordData, { id: "agent-cms/validate.post@1" }) })).output(ValidCodec)
        .errors(pickErrors(cmsErrors, "validationFailed", "schemaDrift")).query(),
      validateUpdate: app.procedure().input(wire.object({ id: wire.string, data: PostUpdateInput })).output(ValidCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).query(),
      syncState: app.procedure().input(IdInput).output(SyncStateCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
      versions: {
        list: app.procedure().input(IdInput).output(PostVersionListCodec)
          .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
        get: app.procedure().input(wire.object({ id: wire.string, versionId: wire.string })).output(PostVersionCodec)
          .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
        restore: app.procedure().input(wire.object({ id: wire.string, versionId: wire.string })).output(PostCodec)
          .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      },
      schedulePublish: app.procedure().input(wire.object({ id: wire.string, at: wire.string })).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      scheduleUnpublish: app.procedure().input(wire.object({ id: wire.string, at: wire.string })).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
      clearSchedule: app.procedure().input(IdInput).output(PostCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(postList).mutation(),
    };
    const authorList = app.procedure().input(wire.object({
      filter: wire.optional(wire.serializable<AuthorFilter>(guard.isFilter, { id: "agent-cms/filter.author@1" })),
      orderBy: wire.optional(wire.array(wire.serializable<AuthorOrderBy>(guard.isOrderBy, { id: "agent-cms/order-by.author@1" }))),
      page: wire.optional(PageInput),
      status: wire.optional(StatusInput),
    })).output(wire.object({ records: wire.array(AuthorCodec), total: wire.integer() }))
      .errors(pickErrors(cmsErrors, "schemaDrift")).query();
    const author = {
      list: authorList,
      byId: app.procedure().input(IdInput).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
      search: app.procedure().input(wire.object({ q: wire.string, page: wire.optional(PageInput) })).output(PickerRowsCodec)
        .errors(pickErrors(cmsErrors, "schemaDrift")).query(),
      create: app.procedure().input(wire.object({ data: AuthorCreateInput })).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "validationFailed", "duplicate", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      update: app.procedure().input(wire.object({ id: wire.string, data: AuthorUpdateInput })).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "duplicate", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      delete: app.procedure().input(IdInput).output(wire.object({ id: wire.string }))
        .errors(pickErrors(cmsErrors, "recordNotFound", "referenceConflict", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      duplicate: app.procedure().input(IdInput).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      publish: app.procedure().input(IdInput).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      unpublish: app.procedure().input(IdInput).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      publishMany: app.procedure().input(IdsInput).output(BulkResultsCodec).errors(mutationErrors).affects(authorList).mutation(),
      unpublishMany: app.procedure().input(IdsInput).output(BulkResultsCodec).errors(mutationErrors).affects(authorList).mutation(),
      deleteMany: app.procedure().input(IdsInput).output(BulkResultsCodec).errors(mutationErrors).affects(authorList).mutation(),
      links: app.procedure().input(IdInput).output(BacklinksCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
      validate: app.procedure().input(wire.object({ data: wire.serializable<Partial<CreateAuthor>>(guard.isRecordData, { id: "agent-cms/validate.author@1" }) })).output(ValidCodec)
        .errors(pickErrors(cmsErrors, "validationFailed", "schemaDrift")).query(),
      validateUpdate: app.procedure().input(wire.object({ id: wire.string, data: AuthorUpdateInput })).output(ValidCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).query(),
      syncState: app.procedure().input(IdInput).output(SyncStateCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
      versions: {
        list: app.procedure().input(IdInput).output(AuthorVersionListCodec)
          .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
        get: app.procedure().input(wire.object({ id: wire.string, versionId: wire.string })).output(AuthorVersionCodec)
          .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
        restore: app.procedure().input(wire.object({ id: wire.string, versionId: wire.string })).output(AuthorCodec)
          .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      },
      schedulePublish: app.procedure().input(wire.object({ id: wire.string, at: wire.string })).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      scheduleUnpublish: app.procedure().input(wire.object({ id: wire.string, at: wire.string })).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "validationFailed", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
      clearSchedule: app.procedure().input(IdInput).output(AuthorCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(authorList).mutation(),
    };
    const assetsList = app.procedure()
      .input(wire.object({ q: wire.optional(wire.string), page: wire.optional(PageInput), orderBy: wire.optional(wire.array(wire.string)) }))
      .output(AssetListCodec).errors(pickErrors(cmsErrors, "schemaDrift")).query();
    const assets = {
      list: assetsList,
      get: app.procedure().input(IdInput).output(AssetRecordCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).query(),
      createUploadUrl: app.procedure().input(wire.object({ filename: wire.string, contentType: wire.string })).output(UploadUrlResultCodec)
        .errors(pickErrors(cmsErrors, "schemaDrift")).errors(mutationErrors).mutation(),
      create: app.procedure().input(wire.object({ data: wire.serializable<AssetCreateInput>(guard.isAssetCreateInput, { id: "agent-cms/AssetCreateInput@1" }) })).output(AssetCreateResultCodec)
        .errors(pickErrors(cmsErrors, "duplicate", "schemaDrift")).errors(mutationErrors).affects(assetsList).mutation(),
      importFromUrl: app.procedure().input(wire.serializable<AssetImportInput>(guard.isAssetImportInput, { id: "agent-cms/AssetImportInput@1" })).output(AssetCreateResultCodec)
        .errors(pickErrors(cmsErrors, "schemaDrift")).errors(mutationErrors).affects(assetsList).mutation(),
      update: app.procedure().input(wire.object({ id: wire.string, data: wire.serializable<AssetUpdateInput>(guard.isAssetUpdateInput, { id: "agent-cms/AssetUpdateInput@1" }) })).output(AssetUpdateResultCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(assetsList).mutation(),
      replace: app.procedure().input(wire.object({ id: wire.string, data: wire.serializable<AssetCreateInput>(guard.isAssetCreateInput, { id: "agent-cms/AssetCreateInput@1" }) })).output(AssetReplaceResultCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "schemaDrift")).errors(mutationErrors).affects(assetsList).mutation(),
      delete: app.procedure().input(wire.object({ id: wire.string, force: wire.optional(wire.boolean) })).output(AssetDeletedCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound", "referenceConflict")).errors(mutationErrors).affects(assetsList).mutation(),
      usages: app.procedure().input(IdInput).output(AssetUsagesCodec)
        .errors(pickErrors(cmsErrors, "recordNotFound")).query(),
    };
  return { post, author, assets };
}
