/* Generated by @agent-cms/codegen — DO NOT EDIT. Regenerate from the CMS schema. */
/* eslint-disable */
/* Server-only: do not import from browser code (result-rpc client boundary). */
import type { ErrorDefinitionMap } from "result-rpc";
import type {
  AnyProcedureTypes,
  ProcedureContract,
  ProcedureImplementationContextConstraint,
  RpcFactory,
} from "result-rpc/server";
import {
  createCmsExecutor,
  decodeOutput,
  decodeRecord,
  decodeRecordPage,
  toQueryOptions,
  toRecord,
  type CmsProceduresDeps,
  type RequestActor,
} from "@agent-cms/codegen/server-runtime";
import {
  cmsContract,
  PostCodec,
  POST_FIELD_KEYS,
  PostVersionCodec,
  PostVersionListCodec,
  AuthorCodec,
  AUTHOR_FIELD_KEYS,
  AuthorVersionCodec,
  AuthorVersionListCodec,
  SyncStateCodec,
  AssetListCodec,
  AssetRecordCodec,
  UploadUrlResultCodec,
  AssetCreateResultCodec,
  AssetUpdateResultCodec,
  AssetReplaceResultCodec,
} from "./contract.ts";
import { mutationErrors } from "./host-errors.js";

/**
 * Server implementations. Spread into the host's own router:
 *   app.router({ ...cmsProcedures(app, contract, { DB: env.DB, actor }), ...hostRouter })
 * where `contract` is the same fragment passed to cmsContract. Handlers run
 * agent-cms's Effect services in-process; `deps.mutationMiddleware` (the host's
 * auth) wraps every mutation, and `deps.actor` records the editor.
 */
export function cmsProcedures<C>(
  app: RpcFactory<C>,
  contract: ReturnType<typeof cmsContract<C>>,
  deps: CmsProceduresDeps<C, typeof mutationErrors>,
) {
  const cms = createCmsExecutor(deps);
  const actorFor = (context: C): RequestActor | null => (deps.actor ? deps.actor(context) : null);
  // The host's gate, applied to every mutation. It is used inline at each site
  // rather than through a generic helper on purpose: result-rpc checks
  // middleware/contract compatibility with conditional types, and those can
  // only evaluate where the procedure's types are concrete. Behind a generic
  // wrapper they stay deferred and nothing typechecks.
  const gate = deps.mutationMiddleware;
  return {
    post: {
      list: app.implement(contract.post.list).handler(async ({ input }) => {
        const r = await cms.query("post", toQueryOptions(input));
        if (r.isErr()) return r;
        return decodeRecordPage(PostCodec, POST_FIELD_KEYS, "post.list", r.value);
      }),
      byId: app.implement(contract.post.byId).handler(async ({ input }) => {
        const r = await cms.byId("post", input.id);
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.byId", r.value);
      }),
      search: app.implement(contract.post.search).handler(async ({ input }) => cms.search("post", input.q, input.page ?? undefined)),
      create: app.implement(contract.post.create).use(gate).handler(async ({ input, context }) => {
        const r = await cms.create("post", toRecord(input.data), actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.create", r.value);
      }),
      update: app.implement(contract.post.update).use(gate).handler(async ({ input, context }) => {
        const r = await cms.update("post", input.id, toRecord(input.data), actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.update", r.value);
      }),
      delete: app.implement(contract.post.delete).use(gate).handler(async ({ input }) => cms.remove("post", input.id)),
      duplicate: app.implement(contract.post.duplicate).use(gate).handler(async ({ input, context }) => {
        const r = await cms.duplicate("post", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.duplicate", r.value);
      }),
      publish: app.implement(contract.post.publish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.publish("post", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.publish", r.value);
      }),
      unpublish: app.implement(contract.post.unpublish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.unpublish("post", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.unpublish", r.value);
      }),
      publishMany: app.implement(contract.post.publishMany).use(gate).handler(async ({ input, context }) => cms.publishMany("post", input.ids, actorFor(context))),
      unpublishMany: app.implement(contract.post.unpublishMany).use(gate).handler(async ({ input, context }) => cms.unpublishMany("post", input.ids, actorFor(context))),
      deleteMany: app.implement(contract.post.deleteMany).use(gate).handler(async ({ input, context }) => cms.deleteMany("post", input.ids, actorFor(context))),
      links: app.implement(contract.post.links).handler(async ({ input }) => cms.links("post", input.id)),
      validate: app.implement(contract.post.validate).handler(async ({ input }) => cms.validate("post", toRecord(input.data))),
      validateUpdate: app.implement(contract.post.validateUpdate).handler(async ({ input }) => cms.validateUpdate("post", input.id, toRecord(input.data))),
      syncState: app.implement(contract.post.syncState).handler(async ({ input }) => {
        const r = await cms.syncState("post", input.id);
        if (r.isErr()) return r;
        return decodeOutput(SyncStateCodec, "post.syncState", r.value);
      }),
      versions: {
        list: app.implement(contract.post.versions.list).handler(async ({ input }) => {
          const r = await cms.versionsList("post", input.id);
          if (r.isErr()) return r;
          return decodeOutput(PostVersionListCodec, "post.versions.list", r.value);
        }),
        get: app.implement(contract.post.versions.get).handler(async ({ input }) => {
          const r = await cms.versionsGet("post", input.id, input.versionId);
          if (r.isErr()) return r;
          return decodeOutput(PostVersionCodec, "post.versions.get", r.value);
        }),
        restore: app.implement(contract.post.versions.restore).use(gate).handler(async ({ input, context }) => {
          const r = await cms.versionsRestore("post", input.id, input.versionId, actorFor(context));
          if (r.isErr()) return r;
          return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.versions.restore", r.value);
        }),
      },
      schedulePublish: app.implement(contract.post.schedulePublish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.schedulePublish("post", input.id, input.at, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.schedulePublish", r.value);
      }),
      scheduleUnpublish: app.implement(contract.post.scheduleUnpublish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.scheduleUnpublish("post", input.id, input.at, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.scheduleUnpublish", r.value);
      }),
      clearSchedule: app.implement(contract.post.clearSchedule).use(gate).handler(async ({ input, context }) => {
        const r = await cms.clearSchedule("post", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(PostCodec, POST_FIELD_KEYS, "post.clearSchedule", r.value);
      }),
    },
    author: {
      list: app.implement(contract.author.list).handler(async ({ input }) => {
        const r = await cms.query("author", toQueryOptions(input));
        if (r.isErr()) return r;
        return decodeRecordPage(AuthorCodec, AUTHOR_FIELD_KEYS, "author.list", r.value);
      }),
      byId: app.implement(contract.author.byId).handler(async ({ input }) => {
        const r = await cms.byId("author", input.id);
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.byId", r.value);
      }),
      search: app.implement(contract.author.search).handler(async ({ input }) => cms.search("author", input.q, input.page ?? undefined)),
      create: app.implement(contract.author.create).use(gate).handler(async ({ input, context }) => {
        const r = await cms.create("author", toRecord(input.data), actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.create", r.value);
      }),
      update: app.implement(contract.author.update).use(gate).handler(async ({ input, context }) => {
        const r = await cms.update("author", input.id, toRecord(input.data), actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.update", r.value);
      }),
      delete: app.implement(contract.author.delete).use(gate).handler(async ({ input }) => cms.remove("author", input.id)),
      duplicate: app.implement(contract.author.duplicate).use(gate).handler(async ({ input, context }) => {
        const r = await cms.duplicate("author", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.duplicate", r.value);
      }),
      publish: app.implement(contract.author.publish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.publish("author", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.publish", r.value);
      }),
      unpublish: app.implement(contract.author.unpublish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.unpublish("author", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.unpublish", r.value);
      }),
      publishMany: app.implement(contract.author.publishMany).use(gate).handler(async ({ input, context }) => cms.publishMany("author", input.ids, actorFor(context))),
      unpublishMany: app.implement(contract.author.unpublishMany).use(gate).handler(async ({ input, context }) => cms.unpublishMany("author", input.ids, actorFor(context))),
      deleteMany: app.implement(contract.author.deleteMany).use(gate).handler(async ({ input, context }) => cms.deleteMany("author", input.ids, actorFor(context))),
      links: app.implement(contract.author.links).handler(async ({ input }) => cms.links("author", input.id)),
      validate: app.implement(contract.author.validate).handler(async ({ input }) => cms.validate("author", toRecord(input.data))),
      validateUpdate: app.implement(contract.author.validateUpdate).handler(async ({ input }) => cms.validateUpdate("author", input.id, toRecord(input.data))),
      syncState: app.implement(contract.author.syncState).handler(async ({ input }) => {
        const r = await cms.syncState("author", input.id);
        if (r.isErr()) return r;
        return decodeOutput(SyncStateCodec, "author.syncState", r.value);
      }),
      versions: {
        list: app.implement(contract.author.versions.list).handler(async ({ input }) => {
          const r = await cms.versionsList("author", input.id);
          if (r.isErr()) return r;
          return decodeOutput(AuthorVersionListCodec, "author.versions.list", r.value);
        }),
        get: app.implement(contract.author.versions.get).handler(async ({ input }) => {
          const r = await cms.versionsGet("author", input.id, input.versionId);
          if (r.isErr()) return r;
          return decodeOutput(AuthorVersionCodec, "author.versions.get", r.value);
        }),
        restore: app.implement(contract.author.versions.restore).use(gate).handler(async ({ input, context }) => {
          const r = await cms.versionsRestore("author", input.id, input.versionId, actorFor(context));
          if (r.isErr()) return r;
          return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.versions.restore", r.value);
        }),
      },
      schedulePublish: app.implement(contract.author.schedulePublish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.schedulePublish("author", input.id, input.at, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.schedulePublish", r.value);
      }),
      scheduleUnpublish: app.implement(contract.author.scheduleUnpublish).use(gate).handler(async ({ input, context }) => {
        const r = await cms.scheduleUnpublish("author", input.id, input.at, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.scheduleUnpublish", r.value);
      }),
      clearSchedule: app.implement(contract.author.clearSchedule).use(gate).handler(async ({ input, context }) => {
        const r = await cms.clearSchedule("author", input.id, actorFor(context));
        if (r.isErr()) return r;
        return decodeRecord(AuthorCodec, AUTHOR_FIELD_KEYS, "author.clearSchedule", r.value);
      }),
    },
    assets: {
      list: app.implement(contract.assets.list).handler(async ({ input }) => {
        const r = await cms.assetsList({ query: input.q ?? undefined, page: input.page ?? undefined, orderBy: input.orderBy ? [...input.orderBy] : undefined });
        if (r.isErr()) return r;
        return decodeOutput(AssetListCodec, "assets.list", r.value);
      }),
      get: app.implement(contract.assets.get).handler(async ({ input }) => {
        const r = await cms.assetsGet(input.id);
        if (r.isErr()) return r;
        return decodeOutput(AssetRecordCodec, "assets.get", r.value);
      }),
      createUploadUrl: app.implement(contract.assets.createUploadUrl).use(gate).handler(async ({ input }) => {
        const r = await cms.assetsCreateUploadUrl({ filename: input.filename, mimeType: input.contentType });
        if (r.isErr()) return r;
        return decodeOutput(UploadUrlResultCodec, "assets.createUploadUrl", r.value);
      }),
      create: app.implement(contract.assets.create).use(gate).handler(async ({ input, context }) => {
        const r = await cms.assetsCreate(input.data, actorFor(context));
        if (r.isErr()) return r;
        return decodeOutput(AssetCreateResultCodec, "assets.create", r.value);
      }),
      importFromUrl: app.implement(contract.assets.importFromUrl).use(gate).handler(async ({ input, context }) => {
        const r = await cms.assetsImportFromUrl(input, actorFor(context));
        if (r.isErr()) return r;
        return decodeOutput(AssetCreateResultCodec, "assets.importFromUrl", r.value);
      }),
      update: app.implement(contract.assets.update).use(gate).handler(async ({ input, context }) => {
        const r = await cms.assetsUpdate(input.id, input.data, actorFor(context));
        if (r.isErr()) return r;
        return decodeOutput(AssetUpdateResultCodec, "assets.update", r.value);
      }),
      replace: app.implement(contract.assets.replace).use(gate).handler(async ({ input, context }) => {
        const r = await cms.assetsReplace(input.id, input.data, actorFor(context));
        if (r.isErr()) return r;
        return decodeOutput(AssetReplaceResultCodec, "assets.replace", r.value);
      }),
      delete: app.implement(contract.assets.delete).use(gate).handler(async ({ input }) => cms.assetsDelete(input.id, input.force ?? false)),
      usages: app.implement(contract.assets.usages).handler(async ({ input }) => cms.assetsUsages(input.id)),
    },
  };
}
