/* eslint-disable */
/* prettier-ignore */
/**
 * This file is auto-generated by gql.tada.
 * Run `pnpm run generate` after `pnpm install` to regenerate.
 *
 * Stub file — the real generated output replaces this after running:
 *   pnpm run introspect   # fetch schema from running CMS
 *   pnpm run generate     # generate TypeScript types
 */
import type { introspection as introspectionType } from "gql.tada";

declare module "gql.tada" {
  interface setupSchema {
    introspection: introspectionType;
  }
}
